# Generated by Django 5.0.1 on 2024-02-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('tech', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='projects')),
            ],
        ),
    ]
